# Generated by Django 6.0.5 on 2026-05-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_avatar_alter_user_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="paid_course",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paid_lesson",
        ),
    ]
