# Generated by Django 6.0.5 on 2026-05-20 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_course_autor_course_lesson_autor_lesson"),
        ("users", "0003_remove_payment_paid_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons.course",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons.lesson",
            ),
        ),
    ]
