# Generated by Django 6.0.5 on 2026-05-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_paid_course_payment_paid_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
