# Generated by Django 6.0.5 on 2026-05-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="pay_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_form",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Наличные"), ("non-cash", "Безналичные")],
                null=True,
            ),
        ),
    ]
