# Generated by Django 6.0.5 on 2026-05-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_date_alter_payment_pay_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="pay_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
