# Generated by Django 6.0.5 on 2026-05-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_pay_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="pay_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
