# Generated by Django 6.0.5 on 2026-05-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payment_pay_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="paid_course",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="paid_lesson",
            new_name="lesson",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="pay_amount",
        ),
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
