# Generated by Django 6.0.5 on 2026-05-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_paid_course_payment_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
