# Generated by Django 6.0.5 on 2026-06-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
