# Generated by Django 6.0.5 on 2026-06-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="users/payments/"),
        ),
    ]
