# Generated by Django 6.0.5 on 2026-05-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_course_autor_course_lesson_autor_lesson"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="autor_course",
            new_name="author_course",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="autor_lesson",
            new_name="author_lesson",
        ),
    ]
