# Generated by Django 6.0.5 on 2026-05-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="author_course",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="author_lesson",
            new_name="owner",
        ),
    ]
