# Generated by Django 6.0.5 on 2026-05-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_rename_author_course_course_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
