# Generated by Django 6.0.5 on 2026-05-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0008_course_price_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
