# Generated by Django 6.0.5 on 2026-06-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0009_course_last_update"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="last_update",
            new_name="updated_at",
        ),
    ]
